"""Allow some players to hide their stuff

Revision ID: 940898f2b2f8
Revises: cccab2478eac
Create Date: 2020-03-24 23:39:57.500796+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940898f2b2f8'
down_revision = 'cccab2478eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'hidden')
    # ### end Alembic commands ###
